---
# tasks file for ansible-role-restic
- name: restic - download and install
  ansible.builtin.get_url:
    url: '{{ restic_download_url }}'
    dest: /tmp

- name: restic - Ensure temporary extract dir is absent
  ansible.builtin.file:
    path: '/tmp/{{ restic_filename_exe }}'
    state: absent

- name: restic - Check that {{ restic_filename_exe }} exists
  ansible.builtin.stat:
    path: '/tmp/{{ restic_filename_exe }}'
  register: stat_result

- name: restic - extract
  ansible.builtin.shell: 'bzip2 -d /tmp/{{ restic_filename_zip }}'

- name: restic - copy to install dir
  ansible.builtin.copy:
    src: '/tmp/{{ restic_filename_exe }}'
    dest: '{{ restic_install_folder }}/restic'
    remote_src: yes
    owner: '{{ restic_file_owner }}'
    group: '{{ restic_file_group }}'
    mode: '{{ restic_file_mode }}'

- name: restic - Delete temporary extract dir
  ansible.builtin.file:
    path: '/tmp/{{ restic_filename_exe }}'
    state: absent
