---
# tasks file for ansible-role-restic
- name: Download
  ansible.builtin.get_url:
    url: '{{ restic_download_url }}'
    dest: /tmp

- name: Check if {{ restic_filename_exe }} exists
  ansible.builtin.stat:
    path: '/tmp/{{ restic_filename_exe }}'
  register: stat_result

- name: Extract
  ansible.builtin.shell: 'bzip2 -d /tmp/{{ restic_filename_zip }}'
  when: stat_result.stat.exists == false

- name: Copy to install dir
  ansible.builtin.copy:
    src: '/tmp/{{ restic_filename_exe }}'
    dest: '{{ restic_install_folder }}/restic'
    remote_src: yes
    owner: '{{ restic_file_owner }}'
    group: '{{ restic_file_group }}'
    mode: '{{ restic_file_mode }}'
